-- Galería de imágenes administrable (carrusel público de la Home).
--
-- Etapa 1 de la feature (ver docs/galeria.md): crea la tabla `gallery_items`
-- como una unidad de contenido independiente (una FOTO), sin FK a `events` ni
-- columnas `localidad`/`fecha`/`is_visible` — a propósito, así lo pidió el
-- relevamiento previo. El carrusel público (`Main.jsx`) todavía NO lee de
-- esta tabla en esta etapa: sigue mostrando el array hardcodeado de siempre
-- hasta la etapa 2.
--
-- CÓMO CORRER ESTA MIGRACIÓN: pegar el archivo completo en el SQL Editor de
-- Supabase y ejecutarlo de una sola vez. Corre dentro de una única
-- transacción explícita (`begin;` / `commit;` más abajo): si cualquier paso
-- falla, no queda nada de este archivo aplicado.
--
-- SUPUESTOS QUE NO SE PUDIERON VERIFICAR CONTRA LA BASE REAL (sin acceso
-- directo a Supabase desde este entorno — confirmar antes/después de correr):
--
-- 1) Tipo de PK: se usa `bigint generated by default as identity` (el
--    default de Supabase para tablas nuevas creadas desde el Table Editor).
--    No hay ninguna migración de creación de tabla versionada en este repo
--    para `events`/`inscriptions` que permita confirmar qué tipo de PK usan
--    esas tablas — se eligió esto por ser el estándar de Supabase y por
--    consistencia con cómo el frontend ya trata todos los `id` existentes
--    (comparaciones numéricas simples, sin parseo de UUID en ningún lado).
--
-- 2) Función `is_admin()`: las policies de la Sección 3 la reutilizan tal
--    cual, SIN redefinirla acá. Su existencia no está versionada como
--    migración en este repo — lo único que hay es la referencia en
--    `claude/commands/fix-rls-api-admin.md`, que dice haberla probado con
--    impersonate en el SQL Editor contra la sesión de un admin real (data
--    point real, pero no una migración versionada). ANTES de correr la
--    Sección 3, confirmar que existe:
--        select proname from pg_proc where proname = 'is_admin';
--    Si no devuelve fila, este archivo va a fallar en el `create policy` con
--    "function is_admin() does not exist" — no adivinar su definición, hay
--    que confirmarla contra la base real primero (y si hace falta crearla,
--    coordinar con quien haya definido las policies de `profiles`/
--    `invalid_emails`, que ya dependen de ella).
--
-- 3) RLS de `events`/`inscriptions`/`event_games` sigue sin poder
--    confirmarse desde este repo (ver docs/supabase.md, sección "RLS /
--    permisos") — no afecta a esta migración, se menciona para no dar a
--    entender que este archivo resuelve o depende de eso.

begin;

-- ============================================================================
-- Sección 1: tabla `gallery_items`
-- ============================================================================
-- image_path: PATH real del archivo en Supabase Storage (bucket `galeria`,
-- ver 20260810_gallery_storage_policies.sql), no la URL pública completa —
-- pedido explícito para poder borrar el archivo físico cuando se borra la
-- fila. La URL pública se deriva en runtime con
-- `supabase.storage.from('galeria').getPublicUrl(image_path)`, nunca se
-- persiste acá.
--
-- title/subtitle: texto libre, sin ningún significado fijo (no son
-- "localidad"/"fecha") — `not null default ''` para que el frontend nunca
-- tenga que lidiar con `null` en un campo de texto libre.
--
-- sort_order: posición en el carrusel, la administra el frontend (altas al
-- final, subir/bajar intercambia valores entre vecinos). No lleva UNIQUE a
-- propósito: con máximo 15 filas administradas a mano desde un único panel
-- admin, el frontend se encarga de no dejar duplicados en el flujo normal
-- (ver GalleryList.jsx) y un UNIQUE agregaría una fuente más de errores a
-- manejar (por ejemplo, durante el intercambio de dos posiciones) sin
-- necesidad real a esta escala.
create table if not exists gallery_items (
    id bigint generated by default as identity primary key,
    image_path text not null,
    title text not null default '',
    subtitle text not null default '',
    sort_order integer not null,
    created_at timestamptz not null default now()
);

-- ============================================================================
-- Sección 2: límite de 15 registros — protección definitiva en la base
-- ============================================================================
-- Mismo patrón que ya usa este proyecto para reglas de negocio (ver
-- supabase/migrations/20260804_event_participation_rules.sql): un trigger
-- que rechaza el INSERT con un marcador identificable
-- (`GALLERY_ITEMS_LIMIT_EXCEEDED`, errcode custom `LCE06` — continúa la
-- numeración de LCE01-LCE05 ya usada en esa migración), que el frontend
-- traduce a un mensaje de usuario (ver src/utils/galleryRules.js).
--
-- A diferencia del límite de juegos por inscripción (que necesitó un trigger
-- de SENTENCIA con tabla de transición por los inserts multi-fila reales de
-- `games_inscriptions`), acá alcanza con `BEFORE INSERT FOR EACH ROW`: el
-- flujo de la app siempre inserta una fila de `gallery_items` a la vez (una
-- foto por alta, ver GalleryList.jsx). No se complica con tabla de
-- transición porque no hay un caso real de insert multi-fila que cubrir.
--
-- Concurrencia: dos altas simultáneas podrían ambas leer "14" antes de que
-- cualquiera haga commit y las dos pasar, dejando 16 filas. Se cierra ese
-- hueco con `lock table ... in share row exclusive mode` al principio del
-- trigger: la segunda transacción concurrente queda esperando ese lock hasta
-- que la primera hace commit/rollback, y recién ahí cuenta el total real ya
-- actualizado. Es un lock de tabla completa, pero sobre una tabla chica (tope
-- 15 filas) con escritura poco frecuente (altas manuales desde un panel
-- admin, no un flujo de alto tráfico) — no compite con las lecturas públicas
-- del carrusel (un SELECT no pide este lock). Esto NO se probó contra una
-- instancia real con dos sesiones concurrentes (mismo aviso que ya deja
-- 20260804_event_participation_rules.sql para su propio mecanismo de
-- concurrencia) — análisis estático únicamente.
create or replace function enforce_gallery_items_limit()
returns trigger
language plpgsql
as $$
declare
    v_cantidad integer;
begin
    lock table gallery_items in share row exclusive mode;

    select count(*) into v_cantidad from gallery_items;

    if v_cantidad >= 15 then
        raise exception 'GALLERY_ITEMS_LIMIT_EXCEEDED'
            using errcode = 'LCE06',
                  detail = format('La galería ya tiene %s imágenes (máximo 15).', v_cantidad);
    end if;

    return new;
end;
$$;

drop trigger if exists trg_enforce_gallery_items_limit on gallery_items;
create trigger trg_enforce_gallery_items_limit
    before insert on gallery_items
    for each row
    execute function enforce_gallery_items_limit();

-- ============================================================================
-- Sección 3: RLS
-- ============================================================================
-- Lectura pública (el carrusel de la Home no requiere login — hoy ni
-- siquiera lee de esta tabla, pero la policy se deja lista para la etapa 2).
-- Alta/edición/borrado solo para admin, vía `is_admin()` (ver el aviso sobre
-- esta función al principio del archivo).
alter table gallery_items enable row level security;

drop policy if exists gallery_items_select_public on gallery_items;
create policy gallery_items_select_public
    on gallery_items
    for select
    using (true);

drop policy if exists gallery_items_insert_admin on gallery_items;
create policy gallery_items_insert_admin
    on gallery_items
    for insert
    with check (is_admin());

drop policy if exists gallery_items_update_admin on gallery_items;
create policy gallery_items_update_admin
    on gallery_items
    for update
    using (is_admin())
    with check (is_admin());

drop policy if exists gallery_items_delete_admin on gallery_items;
create policy gallery_items_delete_admin
    on gallery_items
    for delete
    using (is_admin());

commit;
